### ISSUE TITLE
Add GraalVM to test matrix

### ISSUE THREAD

**Issue by seancorfield** [seancorfield/next-jdbc#162]
Per @delaguardo on Slack:
```
name: Clojure CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '8', '11', '14', '15', '16-ea', '17-ea' ]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@master
        with:
          tools-deps: '1.10.1.739'
      - name: Run Tests
        run: clojure -M:test:runner
  build-graalvm:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        graalvm: [ '19.3.0', '20.0.0', '20.1.0', '20.2.0', '20.3.0', '20.3.1', '20.3.1.2', '21.0.0', '21.0.0.2' ]
        base: [ 'java8', 'java11' ]
    steps:
      - uses: actions/checkout@v2
      - name: Setup GraalVM
        uses: DeLaGuardo/setup-graalvm@4.0
        with:
          graalvm: ${{ matrix.graalvm }}
          java: ${{ matrix.base }}
      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@master
        with:
          tools-deps: '1.10.1.739'
      - name: Run Tests
        run: clojure -M:test:runner
```
